config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :users
  get '/trainers', to: 'users#trainers'

  post '/users/edit', to: 'users#update'
  # get 'my_page', to: 'users#show'
  resources :subscriptions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :user_subscriptions
  has_many :users, through: :user_subscriptions

  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_subscriptions
  has_many :subscriptions, through: :user_subscriptions

  enum role: [:admin, :trainers, :sportsman ]
  after_initialize :set_default_role, :if => :new_record?

  # scope :published, -> { where(published: true) }
  # scope :trainer, -> { where(role: "trainer")}

  def set_default_role
    self.role ||= :sportsman
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  validates :full_name, presence: true, length: {in: 6..50}


  # device authentication with facebook
  def self.from_omniauth(auth) # OmniAuth for facebook
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end

end

app/models/user_subscription.rb
class UserSubscription < ApplicationRecord
  belongs_to :user
  belongs_to :subscription

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery


  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to( root_path )
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = Subscription.all
  end

  def show
    @subscription = Subscription.find(params[:id])
  end

  def update
    @subscription = Subscription.find(params[:id])
    if @subscription.update(subscription_params)
      flash[:notice] = "Saved..."
      redirect_to subscriptions_path
    else
      flash[:alert] = "Не може зберегти"
      render 'edit'
    end
  end

  def edit
    @subscription = Subscription.find(params[:id])
  end


  def delete
    @subscription = Subscription.find(params[:id])
    @subscription.delete
    redirect_to subscriptions_path, :notice => "Абонемент видалено"

  end

  private

  def subscription_params
    params.require(:subscription).permit(:name, :number_of_lessons, :validity, :price )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :authenticate_user!

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    authorize @user

  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    redirect_to users_path, :notice => "User deleted"
  end

  def update
    @user = current_user
    authorize @user
    if @user.role == "admin" # Коли адмін змінює роль чи інші дані користувача
      @admin = User.find(params[:id])
        if @admin.update(admin_params)
          flash[:notice] = "Saved..."
          redirect_to users_path
        else
          flash[:alert] = "Cannot Update..."
          render edit_user_path
        end
    else # Коли звичайний користувач змінює свої дані
      if @user.update(current_user_params)
        flash[:notice] = "Saved..."
        redirect_to user_path(@user)
      else
        flash[:alert] = "Cannot Update..."
        render edit_user_path
      end
    end
  end

  def trainers
    @trainers = User.trainers
  end


  # rescue_from NoMethodError do |errors|
  #   redirect_to root_path, alert: errors.message
  # end
  def admin_params
    params.require(:user).permit(:role, :weight, :height, :from, :about, :sex )
  end

  def current_user_params
    params.require(:user).permit(:weight, :height, :from, :about, :sex )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_subscriptions_helper.rb
module UsersSubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Моя домашня сторінка</h1>
<% if (user_signed_in?) %>
  <%= current_user.email %>
  <%= current_user.role %>
  <%= current_user.id %>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">

    <a href="/" class="navbar-item"><!--root_path-->
      <h3 class="tag is-large is-black">OTAMAN</h3>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
<!--      <a class="navbar-item"></a>-->
      <%= link_to "Тренери", trainers_path, class: "navbar-item"  %>
      <%= link_to "Абонемент", subscriptions_path,class: "navbar-item"  %>
      <a class="navbar-item">Фото Галерея</a>
      <a class="navbar-item">Про Нас</a>

<!--       Відображення чи виконано вхід-->
      <% if (!user_signed_in?) %>

        <div class="navbar-item">
          <div class="buttons">
            <%#= link_to "Реєстрація", new_user_registration_path, class: "button is-primary" %>
            <%= link_to "Увійти", new_user_session_path, class: "button is-light" %>
          </div>
        </div>
      <% else %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-item"><%= current_user.full_name %></a>
          <div class="navbar-dropdown">

            <% if current_user.role == "admin" %><!--Відображення адмінки для адміна-->
              <%= link_to "Admin", users_path, class: "navbar-item" %>
            <% else %> <!-- Відображення інших даних для тренерів та спортсменів -->
              <%= link_to "Моя сторінка", user_path(current_user), class: "navbar-item" %>
              <%= link_to "Налаштування", edit_user_registration_path, class: "navbar-item" %>
            <% end %>
            <hr class="navbar-divider">
            <%= link_to "Вийти", destroy_user_session_path, method: :delete, class: "navbar-item" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>
<script>
    $(document).ready(function() {

        // Check for click events on the navbar burger icon
        $(".navbar-burger").click(function() {

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");

        });
    });
</script>

app/views/subscriptions/index.html.erb
<% @subscriptions.each do |subscription| %>
  <%= subscription.name %>
  <%= subscription.number_of_lessons %>
  <%= subscription.validity %>
  <%= subscription.price %>
  <br/>
<% end %>

app/views/subscriptions/show.html.erb
<h1>my show page <%= @subscription.id %> subscription</h1>
<%= @subscription.name %>
  <%= @subscription.number_of_lessons %>
  <%= @subscription.validity %>
  <%= @subscription.price %>

app/views/users/index.html.erb
<div class="container">
  <div class="box">
    <table class="table-minimal">
      <tbody>

      <% @users.each do |user| %>
        <tr>
          <%#= render user %>
          <td>
            <%= user.id %>
          </td>
          <td>
            <%= link_to user.email, user %>
          </td>
          <td>
            <%= form_for(user) do |f| %>
              <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}, class: "button is-primary is-dropdown") %>

            <td>
              <%= f.submit 'Change Role', class: "button is-dark is-rounded" %>
            </td>
          <% end %>

          <td>
            <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button is-danger is-rounded') unless user == current_user %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">

      <!-- LEFT SIDE -->
      <div class="column is-one-third">
        <div class="columns is-multiline">

          <!-- Верхня карта -->
          <div class="column is-full">
            <div class="card">

              <!--  Фото -->
              <div class="card-content is-horizontal-center is-flex">
                <figure class="image is-256x256">
                  <%= image_tag  'icon_default_avatar.png' %>
                </figure>
              </div>

              <!--  Дані-->
              <div class="card-content">

                <!-- Upload Button -->
                <div class="content has-text-centered">
                  <p class="title is-5">
                    <%= current_user.full_name %>
                  </p>
                  <button class="button is-dark is-outlined is-fullwidth">Оновити Аватар</button>
                </div>

                <!-- Вага -->
                <article>
                  <div class="media">
                    <div class="media-content">Вага</div>
                    <div class="media-right" aria-controls="user-weight">
                      <strong>
                        <% if current_user.weight.presence %><%= current_user.weight %> кг<% else %>(Введіть Вагу)<% end %>
                      </strong><i class="toggle far fa-edit" aria-controls="user-weight"></i>
                    </div>
                  </div>

                  <div class="content">
                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-weight', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_field :weight, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>
                      <a class="toggle button is-light" aria-controls="user-weight">Cancel</a>
                      <%= f.submit "Save", class: "button is-primary" %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Ріст -->
                <article>
                  <div class="media">
                    <div class="media-content">Ріст</div>
                    <div class="media-right">
                      <strong><% if current_user.height.presence %><%= current_user.height %> см<% else %>(Введіть Ріст) <% end %></strong> <i class="toggle far fa-edit" aria-controls="user-height"></i>
                    </div>

                  </div>

                  <div class="content">
                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-height', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_field :height, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>
                      <a class="toggle button is-light" aria-controls="user-height">Cancel</a>
                      <%= f.submit "Save", class: "button is-black" %>
                    <% end %>
                  </div>

                </article>
                <hr class="h-10">

                <!-- Розрахунок індексу маси тіла -->
                <article class="media">
                  <div class="media-content">Індекс маси тіла</div>
                  <div class="media-right">
                    <strong>
                      <% if current_user.height.presence && current_user.weight.presence %>
                        <%= sprintf("%.2f", (current_user.weight)/(current_user.height * current_user.height / 10000.0)).to_f %>
                      <% else %>(Введіть Вагу і Ріст)<% end %>
                    </strong>
                  </div>
                  <br/>
                </article>

              </div>
            </div>
          </div>

          <!-- Нижня карта -->
          <div class="column is-full">
            <div class="card">
              <div class="card-content">

                <!-- Стать -->
                <article>
                  <div class="media">
                    <div class="media-content">Стать</div>
                    <div class="media-right">
                      <strong>
                        <% if current_user.sex.presence %><%=  %><% else %><% end %>
                      </strong>
                    </div>
                  </div>
                </article>

                <hr class="h-10">

                <!-- Languages -->
                <article></article>
                <hr class="h-10">

                <!-- Linked Account -->
                <article class="media"></article>

              </div>
            </div>
          </div>

        </div>
      </div>

      <!-- RIGHT SIDE -->
      <div class="column">
        <div class="card">
          <div class="columns is-multiline">


            <!-- Вибрати абонемент -->
            <div class="column is-one-third has-text-centered">
              <%= image_tag  'icon_add.png' %>
<!--              <h3>Вибрати тренера</h3>-->
            </div>

            <!-- Вибрати Тренера -->
            <div class="column is-one-third has-text-centered">
              <%= image_tag  'icon_add.png'  %>
            </div>

            <!-- Використати абонемент -->
            <div class="column is-one-third has-text-centered ">
              <%= image_tag  'icon_add.png' %>
            </div>
          </div>
        </div>

        <br/>


          <div class="card">
            <div class="column is-multiline">
              <div class="has-text-centered">
                <%#= image_tag 'https://images.climate-data.org/location/498695/temperature-graph.png' %>
              </div>
            </div>
          </div>

      </div>
    </div>
  </div>
</section>

app/views/users/trainer.html.erb
<% @trainers.each do |trainer| %>

  <%= trainer.full_name %>
  <%= trainer.email %>
  <%= trainer.role %>
  <br/>
<% end %>

app/views/users/trainers.html.erb
<section class="mysection">
  <div id="first">
    <h1 class="h1">Тренери</h1>

    <ul class="products clearfix">
      <% @trainers.each do |trainer| %>
        <li class="product-wrapper ">
          <a href="" class="product">
            <% if trainer.image.presence %>
              <%= image_tag trainer.image, class: "product-photo-img" %>
            <% else %>
              <%= image_tag "icon_default_avatar.png", class: "product-photo-img" %>
            <% end %>
            <p class="product-p myborder">
              <%= trainer.full_name %><br/>
            </p>
          </a>
        </li>
      <% end %>
    </ul>

    <div class="clearfix"></div>
  </div>
</section>